# Codecov configuration for pollux
# See https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project: off
    patch: off

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "docs/"
  - "scripts/"
  - "dev/"
  - "notebooks/"
  - "cookbook/"
  - "**/__init__.py"
  - "**/conftest.py"
